apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-mars
spec:
  selector:
    matchLabels:
      planet: mars
  replicas: 1
  template:
    metadata:
      labels:
        planet: mars
    spec:
      containers:
        - name: hello-mars
          image: github.com/stanleynguyen/hello-universe/mars
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: '5000'
---
apiVersion: v1
kind: Service
metadata:
  name: hello-mars
spec:
  selector:
    planet: mars
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer
